### ISSUE TITLE
[Bug] CMS on Gitlab not displaying photos in media assets

### ISSUE THREAD

**Issue by namzo** [netlify/netlify-cms#1436]
I just setup Netlify CMS on my site on Gitlab, I noticed that in the admin, the media page doesn't show my pictures.
<img width="672" alt="screen shot 2018-06-14 at 6 56 22 am" src="https://user-images.githubusercontent.com/1392665/41392404-9aff9e54-6fa0-11e8-9e00-229b26e058f5.png">

When I try to view the image, I noticed the url isn't encoded properly:
<img width="500" alt="screen shot 2018-06-14 at 6 56 35 am" src="https://user-images.githubusercontent.com/1392665/41392473-effce718-6fa0-11e8-973f-b7f8caf38c4e.png">

Steps to reproduce:
- Add Netlify CMS to existing Gitlab site (Not using NPM)
- View the Media assets

**CMS Version**
Netlify CMS version: 1.9.0
Browser version: Chrome 67

**Here's my config file**
```yaml
backend:
  name: gitlab
  repo: namzo/ernestojeh.com
  branch: master
  site_domain: ernestojeh.com

display_url: https://ernestojeh.com
media_folder: "img/post" # Media files will be stored in the repo under images/uploads

collections:
  - name: "writing" # Used in routes, e.g., /admin/collections/blog
    label: "Writing" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
```
Thanks.

**Comment by tech4him1** [comment]
This should be fixed by https://github.com/netlify/netlify-cms/pull/1433.

**Comment by sbuys** [comment]
I'm having the same issue on Git**HUB**. Every once in a while images stop working. Screenshot:

<img width="1274" alt="screen shot 2018-07-09 at 8 52 14 pm" src="https://user-images.githubusercontent.com/340324/42483336-da9492c6-83ba-11e8-830a-ec907488bbd3.png">

**Comment by madisvain** [comment]
@sbuys Yes I can confirm we are facing the same issue with Github as well a bug report was just filed by our client yesterday also about this.

**Comment by Rondieli** [comment]
Hi, looks like I'm still getting this error.  It goes away sometimes after refreshing on the browser (Chrome).

![Screen Shot 2019-11-19 at 8 03 51 AM](https://user-images.githubusercontent.com/20649084/69149042-a442a700-0aa3-11ea-8b2b-3610563b284b.png)

Netlify version 2.9.7

Thank you
