### ISSUE TITLE
Error when uploading multiple images

### ISSUE THREAD

**Issue by victorronnow** [netlify/netlify-cms#3537]
**Describe the bug**

I'm using Cloudinary as the media library.
I have a collection named `article` that has an image field `bottom_gallery` with `multiple: true`.
Whenever I insert multiple images I get this error:
```
netlify-cms.js:48 Uncaught TypeError: e.replace is not a function
    at i (netlify-cms.js:48)
    at t.basename (netlify-cms.js:48)
    at t.getValidateValue (netlify-cms.js:138)
    at Object.bottom_gallery (netlify-cms.js:123)
    at netlify-cms.js:123
    at it.__iterate (netlify-cms.js:1)
    at it.forEach (netlify-cms.js:1)
    at f.validate (netlify-cms.js:123)
    at netlify-cms.js:123
    at Object.onSelection (netlify-cms.js:48)
i @ netlify-cms.js:48
t.basename @ netlify-cms.js:48
(anonymous) @ netlify-cms.js:138
(anonymous) @ netlify-cms.js:123
(anonymous) @ netlify-cms.js:123
it.__iterate @ netlify-cms.js:1
forEach @ netlify-cms.js:1
(anonymous) @ netlify-cms.js:123
(anonymous) @ netlify-cms.js:123
onSelection @ netlify-cms.js:48
u @ netlify-cms.js:114
o.selectItem @ netlify-cms.js:114
s @ netlify-cms.js:76
p @ netlify-cms.js:76
(anonymous) @ netlify-cms.js:76
v @ netlify-cms.js:76
at @ netlify-cms.js:76
it @ netlify-cms.js:76
st @ netlify-cms.js:76
pt @ netlify-cms.js:76
N @ netlify-cms.js:76
U @ netlify-cms.js:76
Jt @ netlify-cms.js:76
Xt @ netlify-cms.js:76
t.unstable_runWithPriority @ netlify-cms.js:84
qi @ netlify-cms.js:76
j @ netlify-cms.js:76
Yt @ netlify-cms.js:76
``` 

**CMS configuration**
```
backend:
  name: git-gateway
  branch: master

media_library:
  name: cloudinary
  config:
    cloud_name: ---
    api_key: ---

media_folder: static/img
public_folder: /img

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - name: 'about'
        label: 'About Page'
        format: 'json'
        file: 'assets/content/about.json'
        fields:
          - { label: 'Contact', name: 'contact', widget: 'text', required: true }
          - { label: 'Body', name: 'body', widget: 'markdown', required: true }
          - { label: 'Team', name: 'team', widget: 'markdown', required: true }
          - { label: 'Thanks', name: 'thanks', widget: 'markdown', required: true }
  - name: 'articles'
    label: 'Articles'
    format: 'json'
    folder: 'assets/content/articles'
    create: true
    slug: "{{year}}--{{month}}--{{day}}--{{slug}}"
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', required: true }
      - { label: 'Thumbnail', name: 'thumbnail', widget: 'image', required: true }
      - { label: 'Top Gallery', name: 'top_gallery', widget: 'image', allow_multiple: true, media_library: { config: { multiple: true, max_files: 50 } }, required: false }
      - { label: 'Bottom Gallery', name: 'bottom_gallery', widget: 'image', allow_multiple: true, media_library: { config: { multiple: true, max_files: 50 } }, required: false }
      - { label: 'Slideshow 1', name: 'slideshow_1', widget: 'image', allow_multiple: true, media_library: { config: { multiple: true, max_files: 50 } }, required: false }
      - { label: 'Slideshow 2', name: 'slideshow_2', widget: 'image', allow_multiple: true, media_library: { config: { multiple: true, max_files: 50 } }, required: false }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
  - name: 'works'
    label: 'Works'
    format: 'json'
    folder: 'assets/content/works'
    create: true
    slug: "{{year}}--{{month}}--{{day}}--{{slug}}"
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', required: true }
      - { label: 'Thumbnail', name: 'thumbnail', widget: 'image', required: true }
      - { label: 'Top Gallery', name: 'top_gallery', widget: 'image', media_library: { config: { multiple: true, max_files: 50 } }, required: false }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
      - { label: 'Stockists', name: 'stockists', widget: 'markdown', required: true }
  - name: 'exhibitions'
    label: 'Exhibitions'
    format: 'json'
    folder: 'assets/content/exhibitions'
    create: true
    slug: "{{year}}--{{month}}--{{day}}--{{slug}}"
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', required: true }
      - { label: 'Gallery', name: 'gallery', widget: 'image', media_library: { config: { multiple: true, max_files: 50 } }, required: false }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
```

The problem is the same with all the other image fields with multiple set to true. Fields with only one image are working.

It worked properly 2-3 days ago but now I don't understand why it's not working.

**To Reproduce**

Steps to reproduce the behavior. For example:
1. Go to article collection in admin panel
2. Click on an article
3. Edit an image field with multiple set to true in config
4. Click publish

**Expected behavior**
The error should be more explicit about why the field is not validated.

**Screenshots**

**Applicable Versions:**
- netlify-cms-app 2.12.3
- netlify-cms.js:68 netlify-cms-core 2.23.3
- netlify-cms.js:183 netlify-cms 2.10.39
 - Git provider: Github
 - OS: macOS 10.14.5
 - Browser version: Chrome Version 80.0.3987.149

 - Node.JS version: v13.8.0

**Comment by erezrokah** [comment]
Thanks for reporting, I submitted a fix here https://github.com/netlify/netlify-cms/pull/3538

**Comment by victorronnow** [comment]
Thanks for fixing this! But looks like I still get the error :( Should I wait for the next version of the cms to make it work?

**Comment by erezrokah** [comment]
Sorry, it was fixed in `master` branch, but not yet released. The next CMS version will contain the fix as you said.

**Comment by victorronnow** [comment]
I'm sorry to bother you again, but when can we expect the new release?

**Comment by erezrokah** [comment]
We'll try to get a release out later on today

**Comment by erezrokah** [comment]
This is released in `netlify-cms@2.10.40`

**Comment by victorronnow** [comment]
Thanks @erezrokah! Unfortunately it is still not published on npm :(

**Comment by erezrokah** [comment]
Oh, you're right, let me check again

**Comment by erezrokah** [comment]
Sorry, now it's in npm
